### ISSUE TITLE
lzma

### ISSUE THREAD

**Issue by shiyi-pan** [Bioconductor/Rhtslib#19]
gcc -std=gnu99 -fPIC -I/ds3512/home/panyp/ruanjian/packages/include  -fpic -I. -fPIC -I/ds3512/home/panyp/ruanjian/packages/include -D_FILE_OFFSET_BITS=64  -c -o cram/open_trace_file.pico cram/open_trace_file.c
gcc -std=gnu99 -fPIC -I/ds3512/home/panyp/ruanjian/packages/include  -fpic -I. -fPIC -I/ds3512/home/panyp/ruanjian/packages/include -D_FILE_OFFSET_BITS=64  -c -o cram/pooled_alloc.pico cram/pooled_alloc.c
gcc -std=gnu99 -fPIC -I/ds3512/home/panyp/ruanjian/packages/include  -fpic -I. -fPIC -I/ds3512/home/panyp/ruanjian/packages/include -D_FILE_OFFSET_BITS=64  -c -o cram/rANS_static.pico cram/rANS_static.c
gcc -std=gnu99 -fPIC -I/ds3512/home/panyp/ruanjian/packages/include  -fpic -I. -fPIC -I/ds3512/home/panyp/ruanjian/packages/include -D_FILE_OFFSET_BITS=64  -c -o cram/sam_header.pico cram/sam_header.c
gcc -std=gnu99 -fPIC -I/ds3512/home/panyp/ruanjian/packages/include  -fpic -I. -fPIC -I/ds3512/home/panyp/ruanjian/packages/include -D_FILE_OFFSET_BITS=64  -c -o cram/string_alloc.pico cram/string_alloc.c
gcc -std=gnu99 -fPIC -I/ds3512/home/panyp/ruanjian/packages/include  -fpic -I. -fPIC -I/ds3512/home/panyp/ruanjian/packages/include -D_FILE_OFFSET_BITS=64  -c -o hfile_libcurl.pico hfile_libcurl.c
gcc -std=gnu99 -shared -Wl,-soname,libhts.so.2 -fPIC -L/ds3512/home/panyp/ruanjian/packages/lib -o libhts.so kfunc.pico knetfile.pico kstring.pico bcf_sr_sort.pico bgzf.pico errmod.pico faidx.pico hfile.pico hfile_net.pico hts.pico hts_os.pico md5.pico multipart.pico probaln.pico realn.pico regidx.pico sam.pico synced_bcf_reader.pico vcf_sweep.pico tbx.pico textutils.pico thread_pool.pico vcf.pico vcfutils.pico cram/cram_codecs.pico cram/cram_decode.pico cram/cram_encode.pico cram/cram_external.pico cram/cram_index.pico cram/cram_io.pico cram/cram_samtools.pico cram/cram_stats.pico cram/files.pico cram/mFILE.pico cram/open_trace_file.pico cram/pooled_alloc.pico cram/rANS_static.pico cram/sam_header.pico cram/string_alloc.pico hfile_libcurl.pico -lz -lm -lbz2 -llzma -lcurl -lpthread
/usr/bin/ld: /ds3512/home/panyp/ruanjian/packages/lib/liblzma.a(liblzma_la-common.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/ds3512/home/panyp/ruanjian/packages/lib/liblzma.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[1]: *** [libhts.so] Error 1
make[1]: Leaving directory `/tmp/RtmpcpTAzn/R.INSTALL71243293e34/Rhtslib/src/htslib-1.7'
make: *** [htslib] Error 2
ERROR: compilation failed for package 'Rhtslib'
* removing '/ds3512/home/panyp/ruanjian/R-4.0.3/lib64/R/library/Rhtslib'

**Comment by hpages** [comment]
Seems to duplicate issue #20. Please don't open twice the same issue.
