### ISSUE TITLE
lzma error when install

### ISSUE THREAD

**Issue by shiyi-pan** [Bioconductor/Rhtslib#20]
Hi, I installed the Rhtslib and met the error ,could you help me fix this problem , thank you very.

gcc -std=gnu99 -fPIC -I/ds3512/home/panyp/ruanjian/packages/include  -fpic -I. -fPIC -I/ds3512/home/panyp/ruanjian/packages/include -D_FILE_OFFSET_BITS=64  -c -o cram/open_trace_file.pico cram/open_trace_file.c
gcc -std=gnu99 -fPIC -I/ds3512/home/panyp/ruanjian/packages/include  -fpic -I. -fPIC -I/ds3512/home/panyp/ruanjian/packages/include -D_FILE_OFFSET_BITS=64  -c -o cram/pooled_alloc.pico cram/pooled_alloc.c
gcc -std=gnu99 -fPIC -I/ds3512/home/panyp/ruanjian/packages/include  -fpic -I. -fPIC -I/ds3512/home/panyp/ruanjian/packages/include -D_FILE_OFFSET_BITS=64  -c -o cram/rANS_static.pico cram/rANS_static.c
gcc -std=gnu99 -fPIC -I/ds3512/home/panyp/ruanjian/packages/include  -fpic -I. -fPIC -I/ds3512/home/panyp/ruanjian/packages/include -D_FILE_OFFSET_BITS=64  -c -o cram/sam_header.pico cram/sam_header.c
gcc -std=gnu99 -fPIC -I/ds3512/home/panyp/ruanjian/packages/include  -fpic -I. -fPIC -I/ds3512/home/panyp/ruanjian/packages/include -D_FILE_OFFSET_BITS=64  -c -o cram/string_alloc.pico cram/string_alloc.c
gcc -std=gnu99 -fPIC -I/ds3512/home/panyp/ruanjian/packages/include  -fpic -I. -fPIC -I/ds3512/home/panyp/ruanjian/packages/include -D_FILE_OFFSET_BITS=64  -c -o hfile_libcurl.pico hfile_libcurl.c
gcc -std=gnu99 -shared -Wl,-soname,libhts.so.2 -fPIC -L/ds3512/home/panyp/ruanjian/packages/lib -o libhts.so kfunc.pico knetfile.pico kstring.pico bcf_sr_sort.pico bgzf.pico errmod.pico faidx.pico hfile.pico hfile_net.pico hts.pico hts_os.pico md5.pico multipart.pico probaln.pico realn.pico regidx.pico sam.pico synced_bcf_reader.pico vcf_sweep.pico tbx.pico textutils.pico thread_pool.pico vcf.pico vcfutils.pico cram/cram_codecs.pico cram/cram_decode.pico cram/cram_encode.pico cram/cram_external.pico cram/cram_index.pico cram/cram_io.pico cram/cram_samtools.pico cram/cram_stats.pico cram/files.pico cram/mFILE.pico cram/open_trace_file.pico cram/pooled_alloc.pico cram/rANS_static.pico cram/sam_header.pico cram/string_alloc.pico hfile_libcurl.pico -lz -lm -lbz2 -llzma -lcurl -lpthread
/usr/bin/ld: /ds3512/home/panyp/ruanjian/packages/lib/liblzma.a(liblzma_la-common.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/ds3512/home/panyp/ruanjian/packages/lib/liblzma.a: could not read symbols: Bad value
collect2: ld returned 1 exit status
make[1]: *** [libhts.so] Error 1
make[1]: Leaving directory `/tmp/RtmpcpTAzn/R.INSTALL71243293e34/Rhtslib/src/htslib-1.7'
make: *** [htslib] Error 2
ERROR: compilation failed for package 'Rhtslib'
* removing '/ds3512/home/panyp/ruanjian/R-4.0.3/lib64/R/library/Rhtslib'

**Comment by hpages** [comment]
What OS are you on? If you are on Windows please install the binary package. Thanks!

**Comment by shiyi-pan** [comment]
thank you for your reply . I installed it in linux redhat OS and trid GCC version 4.4.7 8.3.0, both.

**Comment by hpages** [comment]
Do you have the lzma library on your system? Please show the exact command you are using to install Rhtslib (make sure you are using `BiocManager::install()`) and it full output. Then show your `sessionInfo()`. Thanks.

**Comment by shiyi-pan** [comment]
Thank you for your reply. I used R CMD INSATLL Rhtslib_1.23.0.tar.gz to install the package and here is my lzma library. when I type  ./lzma --help , it print the help file normally:

Usage: ./lzma [OPTION]... [FILE]...
Compress or decompress FILEs in the .xz format.

  -z, --compress      force compression
  -d, --decompress    force decompression
  -t, --test          test compressed file integrity
  -l, --list          list information about .xz files
  -k, --keep          keep (don't delete) input files
  -f, --force         force overwrite of output file and (de)compress links
  -c, --stdout        write to standard output and don't delete input files
  -0 ... -9           compression preset; default is 6; take compressor *and*
                      decompressor memory usage into account before using 7-9!
  -e, --extreme       try to improve compression ratio by using more CPU time;
                      does not affect decompressor memory requirements
  -T, --threads=NUM   use at most NUM threads; the default is 1; set to 0
                      to use as many threads as there are processor cores
  -q, --quiet         suppress warnings; specify twice to suppress errors too
  -v, --verbose       be verbose; specify twice for even more verbose
  -h, --help          display this short help and exit
  -H, --long-help     display the long help (lists also the advanced options)
  -V, --version       display the version number and exit

With no FILE, or when FILE is -, read standard input.

Report bugs to <lasse.collin@tukaani.org> (in English or Finnish).
XZ Utils home page: <https://tukaani.org/xz/>

here is my sessioninfo:

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.5 (Final)

Matrix products: default
BLAS:   /ds3512/home/panyp/ruanjian/R-403/lib64/R/lib/libRblas.so
LAPACK: /ds3512/home/panyp/ruanjian/R-403/lib64/R/lib/libRlapack.so

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] compiler_4.0.3

**Comment by hpages** [comment]
1. The fact that you have the lzma standalone command does not mean that you have the lzma library and its header files. I don't know on CentOS, but on a Debian-based Linux system (e.g. Ubuntu), the former is provided by Debian package `xz-utils` while the latter is provided by Debian package `liblzma-dev`. Please make sure that you have the lzma library and its header files.

2. Do NOT install a Bioconductor package by downloading its source tarball and running `R CMD INSTALL`. This is because each version of a package is tight with a specific version of Bioconductor. In your case, you're trying to install version 1.23.0 of Rhtslib, which is the current devel version so is meant to be used with the current devel version of Bioconductor (BioC 3.13), which itself requires R devel (R 4.1). Mixing packages from different versions of Bioconductor _might_ work sometimes, if you are lucky, but most of the times it will lead to all kinds of ugly problems so it's something that you should absolutely avoid (unless you know what you are doing).

3. As mentioned already, please show the _full output_ of `BiocManager::install("Rhtslib")`.

Thanks

**Comment by hpages** [comment]
@shiyi-pan Were you able to solve the problem?

**Comment by shiyi-pan** [comment]
thank you for your reply. I think is system problem. I can't solve the problem.

**Comment by hpages** [comment]
If you're not going to show me the full output of `BiocManager::install()` (as requested twice already), I can't help you further and we should just close this issue.
