### ISSUE TITLE
error in install package

### ISSUE THREAD

**Issue by gevin-MB** [Bioconductor/Rhtslib#22]
![图片](https://user-images.githubusercontent.com/32149026/109763453-0db0df80-7c2d-11eb-89bf-a1a8b2664860.png)

**Comment by PeteHaitch** [comment]
There's not enough information there for someone to help you. Please provide the full output of running `BiocManager::install("Rhtslib")` as well as the full output of `BiocManager::valid()`. Also, please provide this as text rather than a screenshot.

**Comment by mtmorgan** [comment]
Seems to be the same report as this https://github.com/Bioconductor/Rhtslib/issues/21 , related to Microsoft R Open and an underlying (unknown) issue with liblzma
