### ISSUE TITLE
Rhtslib patch for new R 4.2 UCRT Toolchain

### ISSUE THREAD

**Issue by jwokaty** [Bioconductor/Rhtslib#28]
A patch attempts to be applied at runtime from CRAN; however, it looks like it fails and may not really be needed. It might be good to check before March using `.BBSoptions` that we really don't need the patch at https://www.r-project.org/nosvn/winutf8/ucrt3/patches/BIOC/Rhtslib.diff. To test, we put in `.BBSoptions`

```
INTALLprepend.win: set _R_INSTALL_TIME_PATCHES_=no&&
BUILDprepend.win: set _R_INSTALL_TIME_PATCHES_=no&&
CHECKprepend.win: set _R_INSTALL_TIME_PATCHES_=no&&
BUILDBINprepend.win: set _R_INSTALL_TIME_PATCHES_=no&&
```
to turn off patching and confirm that the package still installs, builds, and passes check. See https://bioconductor.org/checkResults/devel/bioc-LATEST/Rhtslib/palomino3-install.html.

**Comment by hpages** [comment]
Thanks Jennifer. I've disabled automatic patching (commit 164c4d93c1d8aec68160fbed1c1b94a404b46a52). We'll see how it goes.
