### ISSUE TITLE
Install error: ln: failed to create symbolic link 'libhts.so.2': Unknown error 524

### ISSUE THREAD

**Issue by Swilson6** [Bioconductor/Rhtslib#33]
I've tried installing Rhtslib via the BiocManager::install('Rhtslib') command but I get the following error:

ln: failed to create symbolic link 'libhts.so.2': Unknown error 524
make: *** [Makevars:28: populate-usrlib-dir] Error 1
ERROR: compilation failed for package ‘Rhtslib’

Any advice on how to resolve this error?

**Comment by hpages** [comment]
Please show the full output of the `BiocManager::install('Rhtslib')` command + output of your `sessionInfo()`. Thanks
