### ISSUE TITLE
Rhtslib not getting installed

### ISSUE THREAD

**Issue by gbnitdgp** [Bioconductor/Rhtslib#38]
> BiocManager::install("Rhtslib")
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")'
for details.
Replacement repositories:
    CRAN: https://cloud.r-project.org
Bioconductor version 3.20 (BiocManager 1.30.25), R 4.4.2 (2024-10-31)
Installing package(s) 'Rhtslib'
trying URL 'https://bioconductor.org/packages/3.20/bioc/src/contrib/Rhtslib_3.2.0.tar.gz'
Content type 'application/x-gzip' length 5174604 bytes (4.9 MB)
==================================================

hfile_libcurl.c:47:10: fatal error: curl/curl.h: No such file or directory
   47 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[1]: Leaving directory '/tmp/RtmpKMX6hC/R.INSTALL5de373888696/Rhtslib/src/htslib-1.18'
### **make[1]: *** [Makefile.Rhtslib:160: hfile_libcurl.o] Error 1
make: *** [Makevars.common:22: htslib] Error 2
ERROR: compilation failed for package ‘Rhtslib’**
* removing ‘/home/user/R/x86_64-pc-linux-gnu-library/4.4/Rhtslib’
* restoring previous ‘/home/user/R/x86_64-pc-linux-gnu-library/4.4/Rhtslib’

The downloaded source packages are in
	‘/tmp/RtmpsubfLZ/downloaded_packages’
In install.packages(...) :
  installation of package ‘Rhtslib’ had non-zero exit status

**Comment by hpages** [comment]
Do you have `libcurl`?

See https://github.com/Bioconductor/Rhtslib/blob/9373c6f253fd4c2b15789e40bec7bebbc77dcc60/DESCRIPTION#L29 for the system requirements.

If you are on Linux Ubuntu, you can install `libcurl` with `sudo apt-get install libcurl4-openssl-dev`.

**Comment by gbnitdgp** [comment]
Thank you. It solved the problem.
