### ISSUE TITLE
CRAM support requires linking to libcurl

### ISSUE THREAD

**Issue by mtmorgan** [Bioconductor/Rhtslib#7]
I want to update Rsamtools to support CRAM format alignments. htslib supports CRAM, but only when htslib is built linking to libcurl (parsing CRAM requires downloading reference genomes, some reference genomes are only accessible using https, https requires libcurl). Is it possible @hpages to update Rhtslib to (statically?) link to libcurl?

**Comment by hpages** [comment]
Will give this a shot. Don't know how easy this is going to be on Windows though...

**Comment by hpages** [comment]
Rhtslib 1.17.4 now is linked to libcurl. Closing this. Please re-open if you run into problems while trying to support CRAM format alignments in Rsamtools. Thx
